### PR TITLE
rm references to summer 2020

### PR DESCRIPTION
**Pull request by adamjonas**

### CODE REVIEW

**Comment by jnewbery** [comment]
"Chaincode Labs will be running our fifth residency program." sounds very strange to me if it doesn't have a date attached.

**Comment by adamjonas** [comment]
@jnewbery rm references to our fifth iteration.

**Comment by jnewbery** [comment]
I still think the about section sounds very odd. It's talking about a program and cohort that don't exist. We also have no way to know where/when/who'll be involved. I think it's better to make that section more generic and about what our residency program is about in general, or remove the section entirely.

**Comment by adamjonas** [comment]
@jnewbery [updated](https://github.com/chaincodelabs/residency-website/compare/1f094ea..25925fe) to remove specifics and optimism.

**Comment by jnewbery** [comment]
ACK!

**Pull request merged**
